### ISSUE TITLE
Plans for pypi package?

### ISSUE THREAD

**Issue by hdb** [Cvaniak/TextualListViewUnofficial#1]
Hi there- this has been super useful for experimenting with Textual - I'm currently using this in https://github.com/hdb/baywatch. Do you have any plans to publish this to pypi while there is not a built-in scrollable widget list in Textual?

**Comment by Cvaniak** [comment]
So after this widget I decided to create another repo where I would post any widget for Textual that I will need. So after your request here it goes:
* [pypi](https://pypi.org/project/ck-widgets/0.2.0/)
* [github repo](https://github.com/Cvaniak/CvaniaksTextualWidgets)
In short:
``` pip3 install ck-widgets```
```python
 from ck_widgets.widgets import ListViewUo
```
Later I will change this repo because now I will maintain ```ListViewUo``` in [here](https://github.com/Cvaniak/CvaniaksTextualWidgets).

**Comment by hdb** [comment]
Amazing! Thanks!

**Comment by michelececcacci** [comment]
@Cvaniak Could you update the readme and say that the widget can actually be downloaded with pip?  This issue could get buried quite easily, and i feel like this can improve user experience
